# Домашнее задание «Библиотека numpy. Вычислительные задачи»
## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10
np.arange(0, N)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
N = 5
M = np.diag(np.arange(0, N)[::-1])
print(M)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [4]:
np.trace(M)

10

## Задание 3
Решите систему уравнений:
### 4x + 2y + z = 4
### x + 3y = 12
### 5y + 4z = -3

In [5]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
print(a)

[[4 2 1]
 [1 3 0]
 [0 5 4]]


In [6]:
b = np.array( [ 4, 12 , -3 ] )

In [7]:
from numpy import linalg

In [8]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [9]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задача 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [18]:
for user, stats in enumerate(users_stats):
    print(user+1, cosine(stats,next_user_stats))


1 0.19999999999999996
2 0.8451542547285165
3 0.3999999999999999
4 0.7905694150420948
5 0.3999999999999999
6 0.0
7 0.0
8 0.9486832980505138
9 0.0
10 0.0


In [19]:
cosines = [cosine(stats,next_user_stats) for stats in users_stats]
max_cos = max(cosines)
similar_user = cosines.index(max_cos) + 1 

In [25]:
print(f'Cамый похожий пользователь USER ID = {similar_user}, косинусное сходство {round(max_cos,4)}')

Cамый похожий пользователь USER ID = 8, косинусное сходство 0.9487
